config/routes.rb
SoftwareQualityCraft::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end
  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  resources :users, :only => [:show, :index] do
    get 'invite', :on => :member
  end

  #r.results "results", :conditions => {:method => :get}, :action => "index"
  #r.result "results/:survey_code", :conditions => {:method => :get}, :action => "show"
  scope :results do
    match '/results/index' => 'results#index', :via => :get, :as => :results_index
    match '/results/:survey_code' => 'results#show', :via => :get, :as => :results_show
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  helper 'surveyor'
  layout 'results'
  def index
    @surveys = Survey.all
  end

  def show
    @survey = Survey.find_by_access_code(params[:survey_code])
    @response_sets = @survey.response_sets
    @questions = @survey.sections_with_questions.map(&:questions).flatten
  end
end

app/helpers/results_helper.rb
module ResultsHelper
  def display_response(r_set, question)
    sets = get_sets(r_set, question)

    if sets.size == 0
      return_text = "-"
    end

    if sets.size == 1
      return_text = (sets.first.string_value || sets.first.text_value ||
        show_answer(sets.first))
    else
      txt = ""
      sets.each do |set|
        txt << show_answer(set) + "<br/>"
      end
      return_text = txt
    end
    return_text
  end

  def get_sets(r_set, question)
    r_set.responses.select do |r|
      r.question.display_order == question.display_order
    end
  end

  def show_answer(set)
     set.answer.text
  end
end

app/views/results/index.html.erb
<h1>Listing Surveys</h1>

<table class="list_table">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Operation</th>
  </tr>

<% @surveys.each do |survey| -%>
  <tr>
    <td><%=h survey.id %></td>
    <td><%=h survey.title %></td>
    <td><%= link_to "show results list(#{survey.response_sets.count})", results_show_path(survey.access_code) %></td>
  </tr>
<% end %>
</table>

app/views/results/show.html.erb
<table class="list_table">
  <tr>
    <th>ID</th>
    <th>Code</th>
    <% @questions.each do |question| %>
    <% next if question.display_order == 1 %>
    <th><%= "[" +question.display_order.to_s + "]" + question.text  %></th>
    <% end %>
  </tr>

<% @response_sets.each do |r_set| %>
  <tr>
    <td><%=h r_set.id %></td>
    <td><%=h r_set.access_code %></td>
    <% @questions.each do |question| %>
    <% next if question.display_order == 1 %>
    <td><%= display_response(r_set,question) %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to "Back", results_index_path %>